services:
#  app:
#    build:
#      dockerfile: Dockerfile
#    environment:
#      - APP_NAME='ecommerce-product'
#    ports:
#      - 8080:8080
  localstack:
    image: "localstack/localstack"
    environment:
      - SERVICES=dynamodb
      - AWS_DEFAULT_REGION=sa-east-1
    ports:
      - 4566:4566
