@startuml
interface Transaction {
  start(DBConnection connection): void
  findById(PK pk, Function<Object, Model> mapHandler): Model
  add(WriteOperation write): void
  condition(Condition condition):
  commit(Supplier<Model>, Supplier<List<Throwable>): T
  remove(PK id): Boolen

}


class DynamoTransaction implements Transaction {
 - void write(TransactionWriteItems items)
}

interface DBConnection<T> {
   get(): T
}

interface WriteOperation {}
interface ReadOperation {}
interface Condition {}


interface TransactionResult {
  getResult(): Model
  getError(): List<Throwable>
}
@enduml